- name: Ensure base directory exists
  file:
    path: /var/lib/kubernetes
    state: directory
- name: Download kubernetes master binaries
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v{{ kube_master_version }}/bin/linux/amd64/{{ item }}
    dest: /usr/local/bin/{{ item }}
    mode: "755"
  loop: "{{ kube_master_binaries }}"
