- name: Wait for apiserver to start (up to 5 minutes)
  wait_for: port=8080 timeout=300
  register: wait_for_apiserver_result
- name: Pause for apiserver to start fully (20 seconds)
  pause: seconds=20
  when: wait_for_apiserver_result.elapsed|default(0) > 0
