- name: Configure master pods
  template: src={{ item }}.json.j2 dest=/etc/kubernetes/manifests/{{ item }}.json
  loop:
    - apiserver
    - scheduler
    - controller-manager

- include: configure-services.yml
  tags:
  - configure-services
  - configure-services-kube
